import { readFileSync, writeFileSync } from "node:fs";
const p = "docs/TASKS.md";
let s = readFileSync(p, "utf8");
const marker = "## Notes / decisions log\n";
const entry = marker + `
- **2026-09-08 — RESOLVED: the database can be rebuilt from the repo again.** Every UI string added after Phase 1 had been applied straight to the remote project and never committed. The repo held **34 of 193** message keys, so a fresh Supabase project checked out from this repo would have come up with the full schema and almost no strings — rendering \`action.evacuate_now\` at people during a storm. Closed by \`0012_translations_complete.sql\`: 577 rows, 193 keys, three languages, generated by \`npm run db:dump-translations\` and idempotent, so it reconciles rather than conflicts with the subset earlier migrations already insert.

  The deliberate Cebuano gap survived the dump and was checked for: \`action.stay_inside\` and \`headline.stay_inside\` still carry only \`en\` and \`tl\`. That absence is what gives the FR-3.5 fallback path data that actually exercises it, and a future dump showing three languages there would mean it was filled in by accident.

  Only translations were missing. The one schema fix that existed remotely under a name with no local file — \`fix_rescue_rate_limit_execute_grant\` — is already carried by local \`0006\` (\`grant execute on function private.recent_rescue_count() to authenticated\`), verified against \`pg_proc\`. The rest of the remote-only migrations are test scaffolding: row cleanups, temporary signal changes, and role grants keyed to device uids. Those must NOT be replayed on a fresh database and are deliberately not reconstructed.

- **2026-09-08 — The drift is now prevented mechanically, not by discipline.** \`npm run check:i18n\` fails the build when a key the app asks for is not seeded by any migration, and it is in \`verify\`. Dynamic keys (\`t(\\`cat.\\${category}\\`)\` and friends) cannot be read statically, so each such site is declared in the script with the values it can take; an **undeclared** dynamic site fails the check rather than passing silently, because an unknown pattern is a hole in the guard rather than an absence of keys. Verified the way the write-path guard was: a key was planted, the check named the exact key and file and exited 1, and the plant was removed.

- **2026-09-08 — Caveat these files do NOT fix: the remote migration *history* is still divergent.** The 12 local files reproduce the database on a **fresh** project. They will not \`supabase db push\` cleanly against the existing project, because that history was written through the MCP \`apply_migration\` tool under different names (43 entries, e.g. \`foundation_schema_and_rls\`), and \`0001\` would try to \`create table\` over tables that exist. Reconciling that means rewriting the remote migration ledger, which is riskier than the problem and was not attempted. Stand up new environments from these files; leave the existing project as it is.
`;
s = s.replace(marker, entry);
writeFileSync(p, s);
console.log("ok");
