-- Synthetic geography for Barangay San Isidro.
--
-- GENERATED by scripts/generate-synthetic-geo.mjs — edit that, not this file.
--
-- Q4 (a real pilot barangay) is still open and the team chose to proceed on
-- synthetic geography rather than block Phase 4. It is anchored on plausible
-- coordinates near Sta. Cruz, Laguna so distances, zoom and GPS behave
-- realistically, but it is NOT a real barangay and must not be shown as one.
--
-- The geometry lives here rather than in the client because PRD §10 says
-- boundaries and routes are entered by officials during protocol setup. Putting
-- it in the database also means it rides along in the advisory snapshot the app
-- already caches, so the map works offline with no separate fetch or cache.

-- Coordinates for evacuation centres and hazard reports.
--
-- Both were missing them entirely, which made the whole Phase 4 view
-- impossible: a centre with no position cannot be a destination, and a hazard
-- with no position cannot be tested against a route, so "path blocked" could
-- never be computed. Nullable on hazards for the same reason as on
-- rescue_requests — a report must never be blocked on a GPS fix.
alter table public.evac_centers
  add column if not exists lat double precision,
  add column if not exists lng double precision;

alter table public.hazard_reports
  add column if not exists lat double precision,
  add column if not exists lng double precision;

update public.evac_centers set lat = 14.282426, lng = 121.415562 where name = 'Barangay Gym';
update public.evac_centers set lat = 14.277, lng = 121.412781 where name = 'San Roque Chapel';
update public.evac_centers set lat = 14.277, lng = 121.419733 where name = 'San Isidro Elementary School';

update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.41,14.279713],[121.412781,14.279713],[121.412781,14.282426],[121.41,14.282426],[121.41,14.279713]]]}'::jsonb where name = 'Purok 1';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.412781,14.279713],[121.415562,14.279713],[121.415562,14.282426],[121.412781,14.282426],[121.412781,14.279713]]]}'::jsonb where name = 'Purok 2';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.415562,14.279713],[121.418342,14.279713],[121.418342,14.282426],[121.415562,14.282426],[121.415562,14.279713]]]}'::jsonb where name = 'Purok 3';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.418342,14.279713],[121.421123,14.279713],[121.421123,14.282426],[121.418342,14.282426],[121.418342,14.279713]]]}'::jsonb where name = 'Purok 4';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.41,14.277],[121.412781,14.277],[121.412781,14.279713],[121.41,14.279713],[121.41,14.277]]]}'::jsonb where name = 'Purok 5';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.412781,14.277],[121.415562,14.277],[121.415562,14.279713],[121.412781,14.279713],[121.412781,14.277]]]}'::jsonb where name = 'Purok 6';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.415562,14.277],[121.418342,14.277],[121.418342,14.279713],[121.415562,14.279713],[121.415562,14.277]]]}'::jsonb where name = 'Purok 7';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.418342,14.277],[121.421123,14.277],[121.421123,14.279713],[121.418342,14.279713],[121.418342,14.277]]]}'::jsonb where name = 'Purok 8';

update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.41139,14.28107],[121.41139,14.282426],[121.415562,14.282426]]}'::jsonb, route = 'Purok 1 → Barangay Gym · 600 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 1';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.414171,14.28107],[121.414171,14.282426],[121.415562,14.282426]]}'::jsonb, route = 'Purok 2 → Barangay Gym · 300 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 2';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.416952,14.28107],[121.416952,14.282426],[121.415562,14.282426]]}'::jsonb, route = 'Purok 3 → Barangay Gym · 300 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 3';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.419733,14.28107],[121.419733,14.282426],[121.415562,14.282426]]}'::jsonb, route = 'Purok 4 → Barangay Gym · 600 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 4';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.41139,14.278357],[121.41139,14.277],[121.412781,14.277]]}'::jsonb, route = 'Purok 5 → San Roque Chapel · 300 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 5';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.414171,14.278357],[121.414171,14.277],[121.412781,14.277]]}'::jsonb, route = 'Purok 6 → San Roque Chapel · 300 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 6';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.416952,14.278357],[121.416952,14.277],[121.419733,14.277]]}'::jsonb, route = 'Purok 7 → San Isidro Elementary School · 450 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 7';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.419733,14.278357],[121.419733,14.277]]}'::jsonb, route = 'Purok 8 → San Isidro Elementary School · 150 m' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 8';

insert into public.hazard_reports (id, purok_id, category, description, status, lat, lng)
select gen_random_uuid(), pk.id, 'flooding', 'Baha sa Mabini St. — hanggang tuhod', 'open', 14.28107, 121.415562
from public.puroks pk where pk.name = 'Purok 3';

insert into public.hazard_reports (id, purok_id, category, description, status, lat, lng)
select gen_random_uuid(), pk.id, 'fallen_tree', 'Nabuwal na puno sa Luna St.', 'open', 14.280256, 121.418713
from public.puroks pk where pk.name = 'Purok 4';
