-- Real street geometry for Barangay San Isidro.
--
-- GENERATED by scripts/generate-geo.mjs — edit that, not this file.
--
-- Supersedes the geometry in 0008. That migration laid the barangay out as a
-- 4x2 grid of invented 300 m blocks, which was correct while the map drew its
-- own base. Now that the resident map draws OpenStreetMap underneath (see
-- src/lib/basemap.ts), an invented route reads as an instruction to walk
-- through buildings, and the distance printed beside it is not a distance
-- anyone could walk.
--
-- So every route here is a shortest path along surveyed roads, the evacuation
-- centres sit on the network they are reached along, and each Purok boundary is
-- the hull of the streets actually inside it.
--
-- What has NOT changed: the barangay is still fictional. Purok names, centre
-- names and hazards are invented and must never be presented as real. Only the
-- ground they sit on is now true.
--
-- Road geometry (c) OpenStreetMap contributors, ODbL.


update public.evac_centers set lat = 14.282391, lng = 121.415567 where name = 'Barangay Gym';
update public.evac_centers set lat = 14.277355, lng = 121.412793 where name = 'San Roque Chapel';
update public.evac_centers set lat = 14.277117, lng = 121.41977 where name = 'San Isidro Elementary School';

update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.410034,14.282212],[121.410124,14.280428],[121.410839,14.279842],[121.412426,14.279732],[121.412562,14.279821],[121.412645,14.279896],[121.412676,14.279934],[121.412699,14.28007],[121.412218,14.281481],[121.411849,14.282287],[121.411781,14.282401],[121.411045,14.282422],[121.410034,14.282212]]]}'::jsonb where name = 'Purok 1';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.412916,14.280212],[121.412918,14.280192],[121.412927,14.280175],[121.412943,14.280162],[121.413833,14.279794],[121.414255,14.27972],[121.415256,14.279972],[121.415451,14.280759],[121.415548,14.281816],[121.415548,14.281848],[121.415537,14.281878],[121.415518,14.281904],[121.415108,14.282316],[121.413265,14.282051],[121.412916,14.280212]]]}'::jsonb where name = 'Purok 2';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.415567,14.282391],[121.415629,14.280054],[121.417838,14.279841],[121.418054,14.279964],[121.418302,14.280134],[121.418325,14.281663],[121.418246,14.282253],[121.417958,14.282405],[121.415567,14.282391]]]}'::jsonb where name = 'Purok 3';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.418342,14.279713],[121.421123,14.279713],[121.421123,14.282426],[121.418342,14.282426],[121.418342,14.279713]]]}'::jsonb where name = 'Purok 4';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.410396,14.279084],[121.410416,14.278083],[121.410537,14.277899],[121.410915,14.277615],[121.411799,14.277293],[121.412572,14.278209],[121.412753,14.278598],[121.412231,14.279608],[121.410927,14.279657],[121.410396,14.279084]]]}'::jsonb where name = 'Purok 5';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.412781,14.278637],[121.412793,14.277355],[121.41437,14.277129],[121.414974,14.278041],[121.415491,14.278992],[121.414497,14.279623],[121.413986,14.279657],[121.413021,14.279464],[121.412781,14.278637]]]}'::jsonb where name = 'Purok 6';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.415656,14.277503],[121.415707,14.277235],[121.415721,14.277202],[121.415747,14.277179],[121.418049,14.277019],[121.41827,14.277018],[121.41833,14.277197],[121.418325,14.279245],[121.418001,14.279637],[121.415885,14.279065],[121.415682,14.278276],[121.415656,14.277503]]]}'::jsonb where name = 'Purok 7';
update public.puroks set boundary_geojson = '{"type":"Polygon","coordinates":[[[121.418414,14.277353],[121.41937,14.277029],[121.41977,14.277117],[121.420262,14.277339],[121.420578,14.27752],[121.420712,14.278167],[121.420173,14.279044],[121.418609,14.279147],[121.418556,14.278849],[121.418414,14.277353]]]}'::jsonb where name = 'Purok 8';

update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.411623,14.280983],[121.411304,14.280791],[121.411485,14.280488],[121.411679,14.280163],[121.411866,14.279851],[121.412025,14.279584],[121.41206,14.27955],[121.412107,14.279547],[121.412231,14.279608],[121.412781,14.278637],[121.413117,14.279061],[121.413248,14.279229],[121.413484,14.279549],[121.413747,14.279898],[121.413934,14.280131],[121.413983,14.280191],[121.414042,14.28025],[121.41413,14.28032],[121.414213,14.280378],[121.414564,14.280555],[121.414837,14.2807],[121.41503,14.280792],[121.41542,14.28089],[121.415405,14.280954],[121.415867,14.28104],[121.415719,14.281719],[121.415643,14.28203],[121.415613,14.282147],[121.415567,14.282391]]}'::jsonb, route = 'Purok 1 → Barangay Gym · 944 m · Banaba St. → Guiho St. → Antipolo St.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 1';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.413728,14.280714],[121.413934,14.280131],[121.413983,14.280191],[121.414042,14.28025],[121.41413,14.28032],[121.414213,14.280378],[121.414564,14.280555],[121.414837,14.2807],[121.41503,14.280792],[121.41542,14.28089],[121.415405,14.280954],[121.415867,14.28104],[121.415719,14.281719],[121.415643,14.28203],[121.415613,14.282147],[121.415567,14.282391]]}'::jsonb, route = 'Purok 2 → Barangay Gym · 463 m · Zamora St. → Quezon Ave. → Pedro Guevarra Ave.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 2';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.416725,14.281357],[121.416479,14.28133],[121.416438,14.281322],[121.416311,14.281925],[121.416244,14.282238],[121.415613,14.282147],[121.415567,14.282391]]}'::jsonb, route = 'Purok 3 → Barangay Gym · 231 m · A. Mabini St. → Pio Valenzuela St. → M. H. del Pilar St.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 3';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.418876,14.281134],[121.418683,14.281106],[121.41869,14.281057],[121.418207,14.280971],[121.418162,14.2811],[121.418046,14.281586],[121.417967,14.281839],[121.417879,14.282075],[121.417771,14.282212],[121.417642,14.282258],[121.417455,14.282256],[121.417282,14.282231],[121.417082,14.282218],[121.416746,14.282155],[121.416686,14.281992],[121.416311,14.281925],[121.416244,14.282238],[121.415613,14.282147],[121.415567,14.282391]]}'::jsonb, route = 'Purok 4 → Barangay Gym · 530 m · 1st Ave. → Rd. 1 → 1st Ave.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 4';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.411072,14.278488],[121.411368,14.278018],[121.411526,14.27786],[121.411922,14.277454],[121.41216,14.277814],[121.412281,14.277958],[121.41246,14.278185],[121.412484,14.278216],[121.41252,14.278268],[121.412572,14.278209],[121.412793,14.277355]]}'::jsonb, route = 'Purok 5 → San Roque Chapel · 364 m · Floral St. → Quezon Ave.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 5';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.414091,14.278207],[121.413891,14.278642],[121.413789,14.27902],[121.413783,14.279043],[121.413749,14.279163],[121.413701,14.27926],[121.413671,14.279316],[121.413642,14.279373],[121.413484,14.279549],[121.413248,14.279229],[121.413117,14.279061],[121.412781,14.278637],[121.412753,14.278598],[121.41266,14.278469],[121.41252,14.278268],[121.412572,14.278209],[121.412793,14.277355]]}'::jsonb, route = 'Purok 6 → San Roque Chapel · 446 m · Aguinaldo St. → Quezon Ave.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 6';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.417025,14.278618],[121.416878,14.279253],[121.417049,14.279356],[121.417838,14.279841],[121.418054,14.279964],[121.418609,14.279147],[121.419067,14.278333],[121.419234,14.277705],[121.41937,14.277029],[121.41977,14.277117]]}'::jsonb, route = 'Purok 7 → San Isidro Elementary School · 624 m · A. Mabini St. → A. Kamatoy St. → A. Teodoro St.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 7';
update public.protocols p set route_geojson = '{"type":"LineString","coordinates":[[121.419067,14.278333],[121.419234,14.277705],[121.41937,14.277029],[121.41977,14.277117]]}'::jsonb, route = 'Purok 8 → San Isidro Elementary School · 192 m · A. Teodoro St. → Provincial Jail Rd.' from public.puroks pk where pk.id = p.purok_id and pk.name = 'Purok 8';

-- The hazards move with the routes they were placed against.
update public.hazard_reports set lat = 14.281925, lng = 121.416311
  where description = 'Baha sa Mabini St. — hanggang tuhod';
update public.hazard_reports set lat = 14.282051, lng = 121.413265
  where description = 'Nabuwal na puno sa Luna St.';
