-- #5 Callaguip, Batac City, Ilocos Norte — the geography.
--
-- GENERATED by scripts/generate-callaguip.mjs — edit that, not this file.
--
-- Replaces the fictional San Isidro, Sta. Cruz, Laguna. Everything below runs
-- in one transaction, so the app never sees a barangay without areas.
--
-- 1. The old test records are copied into the "archive" schema, which the
--    app's API does not expose, and then cleared. Kept, not destroyed: if any
--    of it is wanted back, it is one INSERT ... SELECT away.
--    Not cleared: user_roles (the real official and volunteer), translations,
--    documents.
--    Not reachable from SQL: 4 hazard photos in the "hazard-photos" storage
--    bucket. Supabase only deletes storage objects through its Storage API,
--    so they are left for the dashboard. They are private and orphaned.
--
-- 2. The barangay becomes #5 Callaguip, at OSM node 8883724672, with an outline
--    traced along the streets that bound it and the population the barangay
--    gave (832, PhilAtlas). The household count is left unset for staff to
--    enter.
--
-- 3. Six areas named after its streets, one evacuation centre at the barangay
--    hall, and a walking route from every area to the hall for signals 1 to 5.
--
-- Road geometry (c) OpenStreetMap contributors, ODbL.

create schema if not exists archive;
revoke all on schema archive from public;

create table archive.barangays_20260919 as table public.barangays;
create table archive.checkins_20260919 as table public.checkins;
create table archive.headcounts_20260919 as table public.headcounts;
create table archive.residents_20260919 as table public.residents;
create table archive.hazard_reports_20260919 as table public.hazard_reports;
create table archive.water_reports_20260919 as table public.water_reports;
create table archive.rescue_requests_20260919 as table public.rescue_requests;
create table archive.signal_history_20260919 as table public.signal_history;
create table archive.protocols_20260919 as table public.protocols;
create table archive.evac_centers_20260919 as table public.evac_centers;
create table archive.puroks_20260919 as table public.puroks;

delete from public.checkins;
delete from public.headcounts;
delete from public.residents;
delete from public.hazard_reports;
delete from public.water_reports;
delete from public.rescue_requests;
delete from public.signal_history;
delete from public.protocols;
delete from public.evac_centers;
delete from public.puroks;

update public.barangays
set name = '#5 Callaguip',
    municipality = 'Batac City',
    province = 'Ilocos Norte',
    current_signal_level = 0,
    storm_name = null,
    bulletin_no = null,
    wind_kph = null,
    evacuate_by = null,
    signal_set_at = null,
    signal_set_by = null,
    expected_households = null,
    lat = 18.0634855,
    lng = 120.5615882,
    boundary_geojson = '{"type":"Polygon","coordinates":[[[120.5592921,18.0617685],[120.559761,18.0633537],[120.5598788,18.0637394],[120.5600084,18.0641282],[120.5600566,18.0642701],[120.5606435,18.0661723],[120.5608783,18.066983],[120.5610119,18.0674254],[120.561069,18.0676144],[120.5611638,18.0679054],[120.561251,18.0681808],[120.5612511,18.0680881],[120.5612699,18.0679924],[120.5613096,18.0678478],[120.5613766,18.0676221],[120.5614577,18.067339],[120.5614444,18.0673176],[120.5614363,18.0672313],[120.5614197,18.0671339],[120.5614353,18.0670092],[120.5615176,18.0664739],[120.5616218,18.0655931],[120.5618771,18.0639882],[120.5619401,18.0635928],[120.5619577,18.0634816],[120.5620777,18.0624689],[120.5621738,18.0618378],[120.5622376,18.0612502],[120.5623784,18.0607251],[120.5624376,18.0604527],[120.5625784,18.0599254],[120.5626518,18.0595657],[120.5628094,18.0590109],[120.5626187,18.0591144],[120.5619696,18.0594413],[120.5615144,18.0596643],[120.5607445,18.0600867],[120.5603179,18.0603096],[120.560553,18.0608209],[120.5602173,18.0610391],[120.5600693,18.0611539],[120.5599951,18.0612157],[120.5599362,18.0612706],[120.5596384,18.0615243],[120.5592921,18.0617685]]]}'::jsonb,
    population = 832,
    population_source = 'PhilAtlas';

insert into public.puroks (barangay_id, name, lat, lng)
select b.id, v.name, v.lat, v.lng
from public.barangays b,
  (values
    ('Asuncion Street', 18.0642701, 120.5600566),
    ('Oeste Street', 18.0603096, 120.5603179),
    ('Otis Street', 18.0590109, 120.5628094),
    ('Rigonan Street', 18.0612502, 120.5622376),
    ('Smith Street', 18.0599254, 120.5625784),
    ('Taft Street', 18.0590109, 120.5628094)
  ) as v(name, lat, lng);

insert into public.evac_centers (purok_id, name, capacity, lat, lng)
select p.id, '#5 Callaguip Barangay Hall', null, 18.0634659, 120.5617101
from public.puroks p
where p.name = 'Asuncion Street';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Asuncion Street → #5 Callaguip Barangay Hall · 190 m · Asuncion St.', '{"type":"LineString","coordinates":[[120.5600566,18.0642701],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Asuncion Street' and c.name = '#5 Callaguip Barangay Hall';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Oeste Street → #5 Callaguip Barangay Hall · 391 m · Oeste St.', '{"type":"LineString","coordinates":[[120.5603179,18.0603096],[120.560553,18.0608209],[120.5609292,18.0617815],[120.5611128,18.0622159],[120.5613363,18.0627722],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Oeste Street' and c.name = '#5 Callaguip Barangay Hall';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Otis Street → #5 Callaguip Barangay Hall · 533 m · Taft St. → Asuncion St.', '{"type":"LineString","coordinates":[[120.5628094,18.0590109],[120.5626518,18.0595657],[120.5625784,18.0599254],[120.5624376,18.0604527],[120.5623784,18.0607251],[120.5622376,18.0612502],[120.5621738,18.0618378],[120.5620777,18.0624689],[120.5619577,18.0634816],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Otis Street' and c.name = '#5 Callaguip Barangay Hall';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Rigonan Street → #5 Callaguip Barangay Hall · 278 m · Taft St. → Asuncion St.', '{"type":"LineString","coordinates":[[120.5622376,18.0612502],[120.5621738,18.0618378],[120.5620777,18.0624689],[120.5619577,18.0634816],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Rigonan Street' and c.name = '#5 Callaguip Barangay Hall';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Smith Street → #5 Callaguip Barangay Hall · 429 m · Taft St. → Asuncion St.', '{"type":"LineString","coordinates":[[120.5625784,18.0599254],[120.5624376,18.0604527],[120.5623784,18.0607251],[120.5622376,18.0612502],[120.5621738,18.0618378],[120.5620777,18.0624689],[120.5619577,18.0634816],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Smith Street' and c.name = '#5 Callaguip Barangay Hall';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Taft Street → #5 Callaguip Barangay Hall · 533 m · Taft St. → Asuncion St.', '{"type":"LineString","coordinates":[[120.5628094,18.0590109],[120.5626518,18.0595657],[120.5625784,18.0599254],[120.5624376,18.0604527],[120.5623784,18.0607251],[120.5622376,18.0612502],[120.5621738,18.0618378],[120.5620777,18.0624689],[120.5619577,18.0634816],[120.5617001,18.0635897]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Taft Street' and c.name = '#5 Callaguip Barangay Hall';

