-- Strings for official access and User Management (0042). Officials-only:
-- reviewed languages, Filipino (= Tagalog) and Ilocano; other languages fall
-- back to Tagalog (acc.* is optional in scripts/generate-translations.mjs).

insert into public.translations (message_key, language, text) values
  ('acc.pin', 'en', 'OFFICIAL PIN'),
  ('acc.pin', 'tl', 'PIN NG OPISYAL'),
  ('acc.pin', 'ceb', 'PIN SA OPISYAL'),
  ('acc.pin', 'fil', 'PIN NG OPISYAL'),
  ('acc.pin', 'ilo', 'PIN TI OPISYAL'),
  ('acc.pin_wrong', 'en', 'Wrong PIN.'),
  ('acc.pin_wrong', 'tl', 'Maling PIN.'),
  ('acc.pin_wrong', 'ceb', 'Sayop nga PIN.'),
  ('acc.pin_wrong', 'fil', 'Maling PIN.'),
  ('acc.pin_wrong', 'ilo', 'Biddut a PIN.'),
  ('acc.unlock', 'en', 'UNLOCK OFFICIAL PAGES'),
  ('acc.unlock', 'tl', 'BUKSAN ANG PAHINA NG OPISYAL'),
  ('acc.unlock', 'ceb', 'ABLIHI ANG PANID SA OPISYAL'),
  ('acc.unlock', 'fil', 'BUKSAN ANG PAHINA NG OPISYAL'),
  ('acc.unlock', 'ilo', 'LUKATAN TI PANID TI OPISYAL'),
  ('acc.not_official', 'en', 'This phone is not an official''s. An official must make it one first (Manage roles).'),
  ('acc.not_official', 'tl', 'Hindi pang-opisyal ang teleponong ito. Kailangan muna itong gawing opisyal ng isang opisyal (Pamahalaan ang mga tungkulin).'),
  ('acc.not_official', 'ceb', 'Dili pang-opisyal kining telepono. Kinahanglan una kining himoon nga opisyal sa usa ka opisyal (Dumala sa mga tahas).'),
  ('acc.not_official', 'fil', 'Hindi pang-opisyal ang teleponong ito. Kailangan muna itong gawing opisyal ng isang opisyal (Pamahalaan ang mga tungkulin).'),
  ('acc.not_official', 'ilo', 'Saan a para iti opisyal daytoy a telepono. Masapul nga aramiden daytoy nga opisyal ti maysa nga opisyal (Imanehar dagiti akem).'),
  ('acc.code_toggle', 'en', 'Have an access code?'),
  ('acc.code_toggle', 'tl', 'May access code ka?'),
  ('acc.code_toggle', 'ceb', 'Naa kay access code?'),
  ('acc.code_toggle', 'fil', 'May access code ka?'),
  ('acc.code_toggle', 'ilo', 'Adda kadi access code-mo?'),
  ('acc.code', 'en', 'ACCESS CODE'),
  ('acc.code', 'tl', 'ACCESS CODE'),
  ('acc.code', 'ceb', 'ACCESS CODE'),
  ('acc.code', 'fil', 'ACCESS CODE'),
  ('acc.code', 'ilo', 'ACCESS CODE'),
  ('acc.code_wrong', 'en', 'Wrong access code.'),
  ('acc.code_wrong', 'tl', 'Maling access code.'),
  ('acc.code_wrong', 'ceb', 'Sayop nga access code.'),
  ('acc.code_wrong', 'fil', 'Maling access code.'),
  ('acc.code_wrong', 'ilo', 'Biddut nga access code.'),
  ('acc.code_locked', 'en', 'Too many wrong codes. Try again in 10 minutes.'),
  ('acc.code_locked', 'tl', 'Masyadong maraming maling code. Subukang muli pagkalipas ng 10 minuto.'),
  ('acc.code_locked', 'ceb', 'Daghan kaayong sayop nga code. Sulayi pag-usab human sa 10 minutos.'),
  ('acc.code_locked', 'fil', 'Masyadong maraming maling code. Subukang muli pagkalipas ng 10 minuto.'),
  ('acc.code_locked', 'ilo', 'Adu unay ti biddut a code. Padasem manen kalpasan ti 10 a minuto.'),
  ('acc.code_off', 'en', 'The access code is switched off.'),
  ('acc.code_off', 'tl', 'Naka-off ang access code.'),
  ('acc.code_off', 'ceb', 'Naka-off ang access code.'),
  ('acc.code_off', 'fil', 'Naka-off ang access code.'),
  ('acc.code_off', 'ilo', 'Naka-off ti access code.'),
  ('acc.lock', 'en', 'LOCK OFFICIAL PAGES'),
  ('acc.lock', 'tl', 'I-LOCK ANG PAHINA NG OPISYAL'),
  ('acc.lock', 'ceb', 'I-LOCK ANG PANID SA OPISYAL'),
  ('acc.lock', 'fil', 'I-LOCK ANG PAHINA NG OPISYAL'),
  ('acc.lock', 'ilo', 'I-LOCK TI PANID TI OPISYAL'),
  ('acc.users', 'en', 'USER MANAGEMENT'),
  ('acc.users', 'tl', 'PAMAMAHALA NG USER'),
  ('acc.users', 'ceb', 'PAGDUMALA SA USER'),
  ('acc.users', 'fil', 'PAMAMAHALA NG USER'),
  ('acc.users', 'ilo', 'PANANGIMANEHAR TI USER'),
  ('acc.users_intro', 'en', 'Change anyone''s role. It applies the next time their app syncs.'),
  ('acc.users_intro', 'tl', 'Baguhin ang tungkulin ng sinuman. Magkakabisa ito sa susunod na pag-sync ng kanilang app.'),
  ('acc.users_intro', 'ceb', 'Usba ang tahas sa bisan kinsa. Magpatuman kini sa sunod nga pag-sync sa ilang app.'),
  ('acc.users_intro', 'fil', 'Baguhin ang tungkulin ng sinuman. Magkakabisa ito sa susunod na pag-sync ng kanilang app.'),
  ('acc.users_intro', 'ilo', 'Baliwan ti akem ti asinoman. Agepekto daytoy iti sumaruno a panag-sync ti app-da.'),
  ('acc.search', 'en', 'Search name or device code'),
  ('acc.search', 'tl', 'Hanapin ang pangalan o device code'),
  ('acc.search', 'ceb', 'Pangitaa ang ngalan o device code'),
  ('acc.search', 'fil', 'Hanapin ang pangalan o device code'),
  ('acc.search', 'ilo', 'Biruken ti nagan wenno device code'),
  ('acc.settings', 'en', 'ACCESS SETTINGS'),
  ('acc.settings', 'tl', 'MGA SETTING SA ACCESS'),
  ('acc.settings', 'ceb', 'MGA SETTING SA ACCESS'),
  ('acc.settings', 'fil', 'MGA SETTING SA ACCESS'),
  ('acc.settings', 'ilo', 'DAGITI SETTING TI ACCESS'),
  ('acc.set_pin', 'en', 'NEW 4-DIGIT PIN'),
  ('acc.set_pin', 'tl', 'BAGONG 4-DIGIT NA PIN'),
  ('acc.set_pin', 'ceb', 'BAG-ONG 4-DIGIT NGA PIN'),
  ('acc.set_pin', 'fil', 'BAGONG 4-DIGIT NA PIN'),
  ('acc.set_pin', 'ilo', 'BARO A 4-DIGIT A PIN'),
  ('acc.save_pin', 'en', 'SAVE PIN'),
  ('acc.save_pin', 'tl', 'I-SAVE ANG PIN'),
  ('acc.save_pin', 'ceb', 'I-SAVE ANG PIN'),
  ('acc.save_pin', 'fil', 'I-SAVE ANG PIN'),
  ('acc.save_pin', 'ilo', 'I-SAVE TI PIN'),
  ('acc.pin_saved', 'en', 'PIN changed. Tell the officials.'),
  ('acc.pin_saved', 'tl', 'Napalitan ang PIN. Sabihan ang mga opisyal.'),
  ('acc.pin_saved', 'ceb', 'Nausab ang PIN. Sultihi ang mga opisyal.'),
  ('acc.pin_saved', 'fil', 'Napalitan ang PIN. Sabihan ang mga opisyal.'),
  ('acc.pin_saved', 'ilo', 'Nabaliwan ti PIN. Ibagam kadagiti opisyal.'),
  ('acc.set_code', 'en', 'NEW ACCESS CODE (8+ CHARACTERS)'),
  ('acc.set_code', 'tl', 'BAGONG ACCESS CODE (8+ KARAKTER)'),
  ('acc.set_code', 'ceb', 'BAG-ONG ACCESS CODE (8+ KARAKTER)'),
  ('acc.set_code', 'fil', 'BAGONG ACCESS CODE (8+ KARAKTER)'),
  ('acc.set_code', 'ilo', 'BARO A ACCESS CODE (8+ KARAKTER)'),
  ('acc.save_code', 'en', 'SAVE CODE'),
  ('acc.save_code', 'tl', 'I-SAVE ANG CODE'),
  ('acc.save_code', 'ceb', 'I-SAVE ANG CODE'),
  ('acc.save_code', 'fil', 'I-SAVE ANG CODE'),
  ('acc.save_code', 'ilo', 'I-SAVE TI CODE'),
  ('acc.code_saved', 'en', 'Access code changed.'),
  ('acc.code_saved', 'tl', 'Napalitan ang access code.'),
  ('acc.code_saved', 'ceb', 'Nausab ang access code.'),
  ('acc.code_saved', 'fil', 'Napalitan ang access code.'),
  ('acc.code_saved', 'ilo', 'Nabaliwan ti access code.'),
  ('acc.code_enabled', 'en', 'ACCESS CODE ON'),
  ('acc.code_enabled', 'tl', 'NAKA-ON ANG ACCESS CODE'),
  ('acc.code_enabled', 'ceb', 'NAKA-ON ANG ACCESS CODE'),
  ('acc.code_enabled', 'fil', 'NAKA-ON ANG ACCESS CODE'),
  ('acc.code_enabled', 'ilo', 'NAKA-ON TI ACCESS CODE'),
  ('acc.code_disabled', 'en', 'ACCESS CODE OFF'),
  ('acc.code_disabled', 'tl', 'NAKA-OFF ANG ACCESS CODE'),
  ('acc.code_disabled', 'ceb', 'NAKA-OFF ANG ACCESS CODE'),
  ('acc.code_disabled', 'fil', 'NAKA-OFF ANG ACCESS CODE'),
  ('acc.code_disabled', 'ilo', 'NAKA-OFF TI ACCESS CODE'),
  ('acc.turn_off', 'en', 'TURN OFF'),
  ('acc.turn_off', 'tl', 'I-OFF'),
  ('acc.turn_off', 'ceb', 'I-OFF'),
  ('acc.turn_off', 'fil', 'I-OFF'),
  ('acc.turn_off', 'ilo', 'I-OFF'),
  ('acc.turn_on', 'en', 'TURN ON'),
  ('acc.turn_on', 'tl', 'I-ON'),
  ('acc.turn_on', 'ceb', 'I-ON'),
  ('acc.turn_on', 'fil', 'I-ON'),
  ('acc.turn_on', 'ilo', 'I-ON'),
  ('acc.not_allowed', 'en', 'Only officials with full access can open User Management.'),
  ('acc.not_allowed', 'tl', 'Ang mga opisyal lang na may buong access ang makakapagbukas ng Pamamahala ng User.'),
  ('acc.not_allowed', 'ceb', 'Ang mga opisyal lang nga adunay bug-os nga access ang makaabli sa Pagdumala sa User.'),
  ('acc.not_allowed', 'fil', 'Ang mga opisyal lang na may buong access ang makakapagbukas ng Pamamahala ng User.'),
  ('acc.not_allowed', 'ilo', 'Dagiti laeng opisyal nga addaan iti naan-anay nga access ti makalukat iti Panangimanehar ti User.'),
  ('acc.none', 'en', 'No users found.'),
  ('acc.none', 'tl', 'Walang nakitang user.'),
  ('acc.none', 'ceb', 'Walay nakit-an nga user.'),
  ('acc.none', 'fil', 'Walang nakitang user.'),
  ('acc.none', 'ilo', 'Awan ti nasarakan a user.'),
  ('acc.via_code', 'en', 'VIA ACCESS CODE'),
  ('acc.via_code', 'tl', 'SA ACCESS CODE'),
  ('acc.via_code', 'ceb', 'PINAAGI SA ACCESS CODE'),
  ('acc.via_code', 'fil', 'SA ACCESS CODE'),
  ('acc.via_code', 'ilo', 'BABAEN TI ACCESS CODE'),
  ('acc.hold_role', 'en', 'Press and hold to make them {n}'),
  ('acc.hold_role', 'tl', 'Pindutin nang matagal para gawing {n}'),
  ('acc.hold_role', 'ceb', 'Pindota ug dugay aron himoon silang {n}'),
  ('acc.hold_role', 'fil', 'Pindutin nang matagal para gawing {n}'),
  ('acc.hold_role', 'ilo', 'Ipindot a nabayag tapno agbalinda a {n}'),
  ('acc.role_saved', 'en', 'Role changed.'),
  ('acc.role_saved', 'tl', 'Napalitan ang tungkulin.'),
  ('acc.role_saved', 'ceb', 'Nausab ang tahas.'),
  ('acc.role_saved', 'fil', 'Napalitan ang tungkulin.'),
  ('acc.role_saved', 'ilo', 'Nabaliwan ti akem.'),
  ('acc.invalid', 'en', 'That is not valid. Check it and try again.'),
  ('acc.invalid', 'tl', 'Hindi wasto. Suriin at subukang muli.'),
  ('acc.invalid', 'ceb', 'Dili husto. Susiha ug sulayi pag-usab.'),
  ('acc.invalid', 'fil', 'Hindi wasto. Suriin at subukang muli.'),
  ('acc.invalid', 'ilo', 'Saan nga umiso. Kitaem ket padasem manen.')
on conflict (message_key, language) do update set text = excluded.text;
