-- Nilombot, Mapandan, Pangasinan — the geography.
--
-- GENERATED by scripts/generate-nilombot.mjs — edit that, not this file.
--
-- Replaces #5 Callaguip, Batac City, Ilocos Norte (migration 0027). Everything
-- below runs in one transaction, so the app never sees a barangay without
-- areas.
--
-- 1. The Callaguip records are copied into the "archive" schema, which the
--    app's API does not expose, and then cleared. Kept, not destroyed: if any
--    of it is wanted back, it is one INSERT ... SELECT away.
--    Not cleared: user_roles, translations, documents, push_subscriptions —
--    those belong to devices and people, not to a place.
--    Not reachable from SQL: any photo in the "hazard-photos" storage bucket.
--    Supabase only deletes storage objects through its Storage API.
--
-- 2. The barangay becomes Nilombot, at OSM node 4369884571, with the OFFICIAL
--    outline from OSM relation 13315002 (admin_level=10, border_type=barangay,
--    PSGC 0105528012) and the population that relation records.
--
--    This is a real improvement on what Callaguip had: its outline was traced
--    along the streets that appeared to bound it, because no boundary relation
--    existed. Nilombot's is the mapped administrative line.
--
-- 3. The areas are the 7 named streets with geometry inside that outline.
--    A Purok list from the barangay should replace them; street names are what
--    the map can prove today.
--
-- 4. One evacuation centre, Nilombot Elementary School (OSM way/790262129).
--    OSM maps no barangay hall inside Nilombot, so none is invented here.
--    Officials can add and move centres on the map.
--
-- 5. Every area gets the five signal protocols, each with the walking route to
--    the centre along real streets.
--
-- Outline area: 225.9 hectares. Population 4411 (PSA 2020 census, via OSM relation 13315002).
--
-- Road and boundary data (c) OpenStreetMap contributors, ODbL.

begin;

create schema if not exists archive;

create table if not exists archive.checkins_20260928 as table public.checkins;
delete from public.checkins;

create table if not exists archive.headcounts_20260928 as table public.headcounts;
delete from public.headcounts;

create table if not exists archive.residents_20260928 as table public.residents;
delete from public.residents;

create table if not exists archive.hazard_reports_20260928 as table public.hazard_reports;
delete from public.hazard_reports;

create table if not exists archive.water_reports_20260928 as table public.water_reports;
delete from public.water_reports;

create table if not exists archive.rescue_requests_20260928 as table public.rescue_requests;
delete from public.rescue_requests;

create table if not exists archive.signal_history_20260928 as table public.signal_history;
delete from public.signal_history;

create table if not exists archive.protocols_20260928 as table public.protocols;
delete from public.protocols;

create table if not exists archive.evac_centers_20260928 as table public.evac_centers;
delete from public.evac_centers;

create table if not exists archive.puroks_20260928 as table public.puroks;
delete from public.puroks;

update public.barangays
set name = 'Nilombot',
    municipality = 'Mapandan',
    province = 'Pangasinan',
    current_signal_level = 0,
    storm_name = null,
    bulletin_no = null,
    wind_kph = null,
    evacuate_by = null,
    signal_set_at = null,
    signal_set_by = null,
    expected_households = null,
    lat = 16.0253207,
    lng = 120.4286234,
    boundary_geojson = '{"type":"Polygon","coordinates":[[[120.4331761,16.0346063],[120.4236478,16.0287637],[120.422194,16.0282946],[120.4199678,16.0275573],[120.4192167,16.0274129],[120.4192401,16.0267701],[120.4201739,16.0268503],[120.4216361,16.0230871],[120.4232454,16.0193438],[120.4247475,16.0158582],[120.4326922,16.0212567],[120.4380888,16.0249277],[120.439843,16.026093],[120.4387652,16.0275246],[120.4386992,16.0276227],[120.4379324,16.0287618],[120.4376864,16.0291607],[120.4376489,16.0292129],[120.4376066,16.0292496],[120.4375979,16.0292825],[120.4375872,16.0293109],[120.4375651,16.0293566],[120.4371016,16.0300336],[120.4368603,16.0303543],[120.4366535,16.0306265],[120.4364563,16.0308796],[120.436081,16.0313614],[120.4351055,16.0326132],[120.435035,16.0327087],[120.4344839,16.0333808],[120.4342076,16.0336978],[120.4340655,16.0338577],[120.4339588,16.033962],[120.4333127,16.0345013],[120.4331761,16.0346063]]]}'::jsonb,
    population = 4411,
    population_source = 'PSA 2020 census, via OSM relation 13315002';

insert into public.puroks (barangay_id, name, lat, lng)
select b.id, v.name, v.lat, v.lng
from public.barangays b,
  (values
    ('Cosmos Street', 16.023214, 120.4294185),
    ('Gumamela Street', 16.0285962, 120.423684),
    ('Orchids Street', 16.0317251, 120.4333721),
    ('Pandan Avenue', 16.027052, 120.4195882),
    ('Rose Street', 16.0321969, 120.4341821),
    ('Santan Street', 16.0273459, 120.4364124),
    ('Zenia Street', 16.0271048, 120.4218762)
  ) as v(name, lat, lng);

insert into public.evac_centers (purok_id, name, capacity, lat, lng)
select p.id, 'Nilombot Elementary School', null, 16.0281798, 120.4362941
from public.puroks p
where p.name = 'Santan Street';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Cosmos Street → Nilombot Elementary School · 1239 m · Cosmos St., Pandan Ave., Santan St.', '{"type":"LineString","coordinates":[[120.4294185,16.023214],[120.4293917,16.0233042],[120.4293649,16.0233906],[120.4293247,16.0234879],[120.429273,16.023602],[120.4292308,16.0237],[120.4292033,16.0237741],[120.4291832,16.023843],[120.4291604,16.0239565],[120.429104,16.0242948],[120.4290833,16.0244154],[120.4290504,16.0245378],[120.4290202,16.0246293],[120.4289371,16.0248427],[120.4288808,16.0249632],[120.4288479,16.0250186],[120.4288043,16.0250663],[120.4287466,16.0251256],[120.4286762,16.0251913],[120.4286159,16.0252487],[120.4285321,16.0253338],[120.4293696,16.0256715],[120.4295553,16.0257424],[120.4296881,16.0257888],[120.4298235,16.0258197],[120.4307301,16.0259692],[120.4308723,16.0260002],[120.4309916,16.0260363],[120.4311325,16.0260859],[120.43175,16.0263592],[120.4318617,16.0264118],[120.4324709,16.0266988],[120.4327565,16.0268483],[120.4330569,16.0270107],[120.4332528,16.0271254],[120.4343377,16.0278279],[120.4345094,16.0279427],[120.4346019,16.0279968],[120.4347789,16.0280909],[120.4349915,16.0281805],[120.4356661,16.0284693],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Cosmos Street' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Gumamela Street → Nilombot Elementary School · 1701 m · Gumamela St., Pandan Ave., Santan St.', '{"type":"LineString","coordinates":[[120.423684,16.0285962],[120.4237162,16.0284512],[120.4237483,16.0282662],[120.4237584,16.0281463],[120.4237671,16.0280187],[120.4237758,16.0279317],[120.4237859,16.0278466],[120.4237953,16.0277796],[120.4238094,16.02769],[120.4238281,16.0276159],[120.4238731,16.0274773],[120.4238972,16.0274219],[120.4239254,16.0273678],[120.4239904,16.0272241],[120.424034,16.0271499],[120.4240699,16.0270993],[120.4241239,16.0270397],[120.4241681,16.0270069],[120.4242385,16.0269669],[120.4242901,16.0269321],[120.4243357,16.0268902],[120.4243653,16.0268535],[120.4243854,16.0268135],[120.4243948,16.0267665],[120.4243988,16.026704],[120.4244538,16.0266769],[120.4245201,16.0266253],[120.4249493,16.0262135],[120.4250626,16.0261162],[120.4251585,16.0260472],[120.4252625,16.025977],[120.4253939,16.0258983],[120.4255287,16.0258281],[120.425703,16.0257508],[120.4258425,16.0257005],[120.4259323,16.0256753],[120.4261241,16.0256251],[120.4265258,16.0255316],[120.4279219,16.0252397],[120.4280352,16.0252216],[120.4281183,16.0252158],[120.4281968,16.0252216],[120.4282786,16.0252364],[120.4283845,16.0252719],[120.4285321,16.0253338],[120.4293696,16.0256715],[120.4295553,16.0257424],[120.4296881,16.0257888],[120.4298235,16.0258197],[120.4307301,16.0259692],[120.4308723,16.0260002],[120.4309916,16.0260363],[120.4311325,16.0260859],[120.43175,16.0263592],[120.4318617,16.0264118],[120.4324709,16.0266988],[120.4327565,16.0268483],[120.4330569,16.0270107],[120.4332528,16.0271254],[120.4343377,16.0278279],[120.4345094,16.0279427],[120.4346019,16.0279968],[120.4347789,16.0280909],[120.4349915,16.0281805],[120.4356661,16.0284693],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Gumamela Street' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Orchids Street → Nilombot Elementary School · 647 m · Rose St., Santan St.', '{"type":"LineString","coordinates":[[120.4333721,16.0317251],[120.4333828,16.0317509],[120.433409,16.0317754],[120.4334915,16.0318244],[120.4336383,16.0318985],[120.4340353,16.0321112],[120.4340504,16.0320886],[120.4340527,16.0320715],[120.4340594,16.0320531],[120.4342016,16.0317702],[120.4343524,16.0314515],[120.4344135,16.0312869],[120.4344517,16.0311722],[120.4344879,16.0310897],[120.4345382,16.0309994],[120.4346294,16.0308312],[120.4347012,16.0306983],[120.4347782,16.0305311],[120.4348145,16.0304072],[120.4348707,16.0302332],[120.4349079,16.0301383],[120.4349498,16.0300574],[120.4351125,16.0296858],[120.4351256,16.0296518],[120.4352108,16.0295287],[120.4352262,16.0295055],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Orchids Street' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Pandan Avenue → Nilombot Elementary School · 1989 m · Pandan Ave., Santan St.', '{"type":"LineString","coordinates":[[120.4195882,16.027052],[120.4197867,16.0270043],[120.4199503,16.0269746],[120.4201354,16.026954],[120.4203755,16.0269463],[120.4207966,16.0269721],[120.4210125,16.0270017],[120.4212861,16.0270468],[120.4215275,16.0270868],[120.4217206,16.0270984],[120.421797,16.0271015],[120.4218762,16.0271048],[120.4220532,16.0270971],[120.4233258,16.0268793],[120.4243357,16.0267188],[120.4243988,16.026704],[120.4244538,16.0266769],[120.4245201,16.0266253],[120.4249493,16.0262135],[120.4250626,16.0261162],[120.4251585,16.0260472],[120.4252625,16.025977],[120.4253939,16.0258983],[120.4255287,16.0258281],[120.425703,16.0257508],[120.4258425,16.0257005],[120.4259323,16.0256753],[120.4261241,16.0256251],[120.4265258,16.0255316],[120.4279219,16.0252397],[120.4280352,16.0252216],[120.4281183,16.0252158],[120.4281968,16.0252216],[120.4282786,16.0252364],[120.4283845,16.0252719],[120.4285321,16.0253338],[120.4293696,16.0256715],[120.4295553,16.0257424],[120.4296881,16.0257888],[120.4298235,16.0258197],[120.4307301,16.0259692],[120.4308723,16.0260002],[120.4309916,16.0260363],[120.4311325,16.0260859],[120.43175,16.0263592],[120.4318617,16.0264118],[120.4324709,16.0266988],[120.4327565,16.0268483],[120.4330569,16.0270107],[120.4332528,16.0271254],[120.4343377,16.0278279],[120.4345094,16.0279427],[120.4346019,16.0279968],[120.4347789,16.0280909],[120.4349915,16.0281805],[120.4356661,16.0284693],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Pandan Avenue' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Rose Street → Nilombot Elementary School · 579 m · Rose St., Santan St.', '{"type":"LineString","coordinates":[[120.4341821,16.0321969],[120.4340913,16.0321424],[120.4340725,16.0321276],[120.4340541,16.0321044],[120.4340504,16.0320886],[120.4340527,16.0320715],[120.4340594,16.0320531],[120.4342016,16.0317702],[120.4343524,16.0314515],[120.4344135,16.0312869],[120.4344517,16.0311722],[120.4344879,16.0310897],[120.4345382,16.0309994],[120.4346294,16.0308312],[120.4347012,16.0306983],[120.4347782,16.0305311],[120.4348145,16.0304072],[120.4348707,16.0302332],[120.4349079,16.0301383],[120.4349498,16.0300574],[120.4351125,16.0296858],[120.4351256,16.0296518],[120.4352108,16.0295287],[120.4352262,16.0295055],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Rose Street' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Santan Street → Nilombot Elementary School · 103 m · Santan St.', '{"type":"LineString","coordinates":[[120.4364124,16.0273459],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Santan Street' and c.name = 'Nilombot Elementary School';

insert into public.protocols (purok_id, signal_level, route, route_geojson, action_key, evac_center_id)
select p.id, s.level, 'Zenia Street → Nilombot Elementary School · 1742 m · Pandan Ave., Santan St.', '{"type":"LineString","coordinates":[[120.4218762,16.0271048],[120.4220532,16.0270971],[120.4233258,16.0268793],[120.4243357,16.0267188],[120.4243988,16.026704],[120.4244538,16.0266769],[120.4245201,16.0266253],[120.4249493,16.0262135],[120.4250626,16.0261162],[120.4251585,16.0260472],[120.4252625,16.025977],[120.4253939,16.0258983],[120.4255287,16.0258281],[120.425703,16.0257508],[120.4258425,16.0257005],[120.4259323,16.0256753],[120.4261241,16.0256251],[120.4265258,16.0255316],[120.4279219,16.0252397],[120.4280352,16.0252216],[120.4281183,16.0252158],[120.4281968,16.0252216],[120.4282786,16.0252364],[120.4283845,16.0252719],[120.4285321,16.0253338],[120.4293696,16.0256715],[120.4295553,16.0257424],[120.4296881,16.0257888],[120.4298235,16.0258197],[120.4307301,16.0259692],[120.4308723,16.0260002],[120.4309916,16.0260363],[120.4311325,16.0260859],[120.43175,16.0263592],[120.4318617,16.0264118],[120.4324709,16.0266988],[120.4327565,16.0268483],[120.4330569,16.0270107],[120.4332528,16.0271254],[120.4343377,16.0278279],[120.4345094,16.0279427],[120.4346019,16.0279968],[120.4347789,16.0280909],[120.4349915,16.0281805],[120.4356661,16.0284693],[120.4357702,16.0285139],[120.4361334,16.0278511],[120.4362941,16.0281798]]}'::jsonb, s.action_key, c.id
from public.puroks p
cross join public.evac_centers c
cross join (values
    (1, 'action.stay_alert'),
    (2, 'action.prepare'),
    (3, 'action.evacuate_now'),
    (4, 'action.evacuate_immediately'),
    (5, 'action.stay_inside')
  ) as s(level, action_key)
where p.name = 'Zenia Street' and c.name = 'Nilombot Elementary School';

commit;
